### ISSUE TITLE
"Fluent Animation" conflicts with Nilesoft Shell context menu

### ISSUE THREAD

**Issue by emvaized** [ALTaleX531/TranslucentFlyouts#109]
When "Fluent Animation" enabled in settings, TranslucentFlyouts tries to animate context menus created by [Nilesoft Shell](https://github.com/moudey/Shell). However, animation doesn't work, and it just creates a delay when popup background is showing with no items in it: 

![2024-03-07172411-ezgif com-video-to-gif-converter](https://github.com/ALTaleX531/TranslucentFlyouts/assets/37851576/8973bb82-34c4-4e94-9ac7-48e53f8f9c1e)

I can think of 2 solutions for this problem: 
1) Fix incompatibility with Nilesoft Shell, so that context menus created by this utility gets animated like the rest of context menus
2) If it's improssible, then don't try to animate context menus from Nilesoft Shell 

Thank you

**Comment by ALTaleX531** [comment]
After a quick look at the code for Nilesoft Shell, I realized that it is highly invasive software because it takes over the rendering of the menus directly, so TranslucentFlyouts doesn't work at all, which means that the two can't be used at the same time. If you wish to have the animation feature, ask Nilesoft Shell to add it.
However, v3 has an undocumented feature and you can mitigate the conflict by creating a new dword value in the registry called explorer.exe and setting it to 1.
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/6cc54fd5-e14a-423a-a983-dc783bf9feaf)

**Comment by emvaized** [comment]
@ALTaleX531 
Thanks, I'll try that!

**Comment by emvaized** [comment]
Hhm, I guess Registry workaround doesn't work for me for some reason... I added the key, restarted the system, but it still tries to animate Nilesoft Shell's menu

**Comment by ALTaleX531** [comment]
Well, I don't know why it doesn't work there, please try creating that dword value in `HKEY_CURRENT_USER\Software\TranslucentFlyouts\Menu\DisabledList`, that shouldn't be a problem. 
I'll remove that stupid detection and introduce a more efficient solution in the next version.

**Comment by emvaized** [comment]
> please try creating that dword value

I did already. Unfortunately, it doesn't solve the problem. 
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/37851576/9ad68fb0-fd68-4073-9bac-400aec886ac5)

**Comment by ALTaleX531** [comment]
Are you using the latest version?

**Comment by emvaized** [comment]
Sorry, I didn't noticed the new release. 

Yes, "DisabledList" registry key works now in latest version. 
However, excluding the whole `explorer.exe` leads to translucity not applied to all tooltips in Explorer (such as details tooltip when hovering any file or folder)

**Comment by ALTaleX531** [comment]
> HKEY_CURRENT_USER\Software\TranslucentFlyouts\Menu\DisabledList

This is why the DisabledList item exists under the Menu subkey, where you can create dword value.

**Comment by emvaized** [comment]
This way it works. Thanks a lot!
